# Generated by Django 3.2 on 2021-11-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_service'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='services',
            field=models.ManyToManyField(to='barbers.Service'),
        ),
    ]
