# Generated by Django 3.2 on 2021-11-19 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=128, verbose_name='Shop Name')),
                ('province', models.CharField(blank=True, max_length=128, null=True, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('address', models.TextField(verbose_name='Shop Address')),
                ('location', models.CharField(blank=True, max_length=512, null=True, verbose_name='Map Location')),
                ('start_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Start Time')),
                ('end_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='End Time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created BarberShop')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Data')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
