# Generated by Django 3.2 on 2021-11-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_barber_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='barber/', verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='barber',
            name='inner_1',
            field=models.ImageField(blank=True, null=True, upload_to='barber/', verbose_name='Inner Picture'),
        ),
        migrations.AddField(
            model_name='barber',
            name='inner_2',
            field=models.ImageField(blank=True, null=True, upload_to='barber/', verbose_name='Inner Picture'),
        ),
        migrations.AddField(
            model_name='barber',
            name='inner_3',
            field=models.ImageField(blank=True, null=True, upload_to='barber/', verbose_name='Inner Picture'),
        ),
    ]
