# Generated by Django 3.2 on 2021-11-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_auto_20211120_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128, verbose_name='Service Name')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created BarberShop')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Data')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_service', to='barbers.barber')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
