# Generated by Django 3.1.1 on 2021-11-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Phone Number'),
        ),
    ]
