# Generated by Django 3.1.1 on 2021-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211119_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Phone Number'),
        ),
    ]
