# Generated by Django 3.2 on 2021-11-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=512, verbose_name='Paid Code')),
                ('authority', models.CharField(max_length=512, verbose_name='Authority Code')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.CharField(choices=[('c', 'Canceled'), ('p', 'Paid'), ('n', 'Not Paid')], default='n', max_length=1, verbose_name='Status')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_payment', to='reservations.reserve')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
